bbox = [29.993002, -172.265625, 62.512318, -87.363281]
resolution = 1
duration = 900
# duration = 120

offset = 40_500

[network_params]
bandwidth_kbits = 10_000_000
min_elevation = 20
ground_station_connection_type = "all"

[compute_params]
vcpu_count = 4
mem_size_mib = 8192
disk_size_mib = 16_384
kernel = "vmlinux-5.15-containerd.bin"
rootfs = "criu.img"

[[shell]]
inclination = 53.0
planes = 1
sats = 22
altitude_km = 550
arc_of_ascending_nodes = 360.0
eccentricity = 0.0

[[ground_station]]
name = "Redmond"
lat = 47.67859
long = -122.13031

[ground_station.compute_params]
vcpu_count = 4
mem_size_mib = 4096
rootfs = "client.img"
